hobbyquaker/awesome-mqtt

README.md

RabbitMQ has a nice plugin for MQTT

Added MQTT Adapter for RabbitMQ

---

README.md

This is useful for people who don't know what MQTT is.
Also fix a typo

Add a short description of MQTT

---

README.md

Add links to hbmqtt, a python client/broker.

Add hbmqtt

---

.travis.yml
README.md

There is a nice project called [awesome_bot](https://github.com/dkhamsing/awesome_bot) which tests the links in a awesome list for there existence and checks if they are valid or not

Added link tests

---

README.md

Add link to https://github.com/hardillb/d3-MQTT-Topic-Tree into Visualization category

Add d3-MQTT-Topic-Tree

---

README.md

Add link to mqtt-wall (https://github.com/bastlirna/mqtt-wall) into Tools section.

Add mqtt-wall

---

README.md

Add link to [MySensors](https://www.mysensors.org/), an excellent library for Arduino and NRF24L01 based wireless sensors. Details about the MQTT gateway are [here](https://www.mysensors.org/build/mqtt_gateway).

Add MySensors library

---

README.md

Add a link to my project of an MQTT broker on an ESP8266. Feel free to move it to the Makers section if you think it belongs to that chapter.

Added the esp_uMQTT_broker

---

README.md

I added the 2 in a single PR for more convenience.
The 2 additions are split in separate commits.

Add Hulaaki (Elixir) and Machine Head (Clojure) clients libraries

---

README.md

Some cleanup and an attempt to standardize capitalization of different terms used.

Minor formatting cleanup

---

README.md

I select the misc section. I haven't found a more suitable one. I hope that's okay.

Added buderus2mqtt and vorwerk2mqtt

---

README.md

Added MQTT-DashCast-Docker

---

README.md

This PR adds Mystique to the list of available MQTT brokers.

Add Mystique

---

README.md

Added reference to the Eclipse IoT-Testware to the tools section

Eclipse IoT-Testware added

---

README.md

Also fixed some extra whitespace

Added flespi broker, MQTT Board tool & gmqtt Python client library

---

README.md

Added MyQtthub.com reference. Fixed some urls moving to 301, causing TravisCI awesome_bot code to failcheck.

Added MyQtthub.com reference

---

README.md

Added a link to the industrial Mqtt Gateway "OPC Router" from inray

Added the Industrial Mqtt Gateway "OPC Router"

---

README.md

Full disclosure: I am co-founder of Teserakt AG

category Security, Encryption; adding Teserakt e2ee

---

README.md

Development of https://github.com/owagner/modbus2mqtt/ has ceased (the developer Mr Wagner has sadly passed away). Development continues here: https://github.com/mbs38/spicierModbus2mqtt

new version of modbus bridge

---

README.md

Add MQTTnet library

---

README.md

A friend of mine and I built a simple Slack app to send messages from Slack to MQTT topics. Perhaps someone also needs something like this. We hope it helps.

Add SimpleMQTT to tools section

---

README.md

added ESP8266Mesh to Interfaces -> Makers

Added PhracturedBlue's ESP8266MQTTMesh

---

README.md

- Add hivemq-mqtt-client
- Add hivemq-mqtt-web-client
- Add mqtt CLI
- Update HiveMQ description to include open source edition

Update Projects by HiveMQ

---

README.md

- Added new section, 
- moved Tasmota to there, 
- added 4 more similar projects,
- added brief description of ESP8266 device class

Add ESP8266 device firmwares

---

README.md

A fast and efficient, but minimalistic Dashboard application  for linux/Raspberry Pi.

Added MQTT-Hyperdash

---

README.md

Adds mqtt-camera-streamer

---

README.md

Add MQTT.Cool product and related web Test Client.

Add MQTT.Cool.

---

README.md

Add Platforms heading to ToC

---

README.md

MQTT Joystick controller, is an app that I developed in order to control Arduino based micro cars. Now I'm trying to use it for my WifFi RPI based quadcopter. Enjoy :+1:

Added MQTT Joystick Controller under Misc

---

README.md

Adding the Ably MQTT broker service to the list of brokers

adding Ably broker to broker list

---

README.md

Add sms2mqtt in telephony category

Add sms2mqtt

---

README.md

I have added the `MQTT TUI` tool by EdjoPaTo. This tool was designed to quickly watch or publish MQTT stuff from the terminal. I find it pleasant and easy to use. It does exactly what it is intended for.

Added MQTT UI tool

---

README.md

[PlotJuggler](https://github.com/facontidavide/PlotJuggler) is a tool to visualize time series (*from sources such as: MQTT, Websockets, ZeroMQ, UDP, etc., supports data formats such as JSON, CBOR, BSON, Message Pack, etc.*). It is a fast, powerful and intuitive cross-platform tool.

Added PlotJuggler

---

README.md

mqtt_monitor for console

---

README.md

MYHELLOIOT is a MQTT dashboard application inspired in my other MQTT project HelloIoT.

add MYHELLOIOT

---

README.md

Add zwavejs2mqtt
